### ISSUE TITLE
Subfolder multisite redirect target not generated correctly

### ISSUE THREAD

**Issue by AndrewHaine** [justkidding96/statamic-aardvark-seo#64]
The source url is handled correctly but the target is not:

In this example we are working on a site in the `/de` subfolder:
```yaml
source_url: /test
target_url: /testing
```

The user gets redirected from `/de/test` to `/testing` instead of `/de/testing`

We probably need to make it clearer in the docs how this works - and possibly make it possible for people to use `/de/test` When inputting the redirect.

**Comment by AndrewHaine** [comment]
Fixed in 2.0.4

**Comment by aerni** [comment]
It looks like this issue still partially remains on version 2.0.6.

```yaml
source_url: /work
target_url: /custom-websites
```

`http://michaelaerni.test/en/work` redirects to `http://michaelaerni.test/custom-websites`.

I need to add a trailing `/` for it to work as expected:

`http://michaelaerni.test/en/work/` correctly redirects to `http://michaelaerni.test/en/custom-websites`.

**Comment by aerni** [comment]
Nevermind. I tried in a new browser window and it works as expected. Odd.
